version: '3.5'
services:
 zabbix-build-base:
  build:
   context: ./Dockerfiles/build-base/ol
   cache_from:
    - oraclelinux:8-slim
  image: zabbix-build-base:ol-6.4.0

 zabbix-build-oracle:
  build:
   context: ./Dockerfiles/build-oracle/ol
   cache_from:
    - oraclelinux:8-slim
   args:
    BUILD_BASE_IMAGE: zabbix-build-base:ol-6.4.0
  image: zabbix-build-oracle:ol-6.4.0
  depends_on:
   - zabbix-build-base

 zabbix-server:
  build:
   context: ./Dockerfiles/server-oracle/ol
   cache_from:
    - oraclelinux:8-slim
   args:
    BUILD_BASE_IMAGE: zabbix-build-oracle:ol-6.4.0
  image: zabbix-server-oracle:ol-6.4.0
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./zbx_env/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
   - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:rw
#   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
#   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
#   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  env_file:
   - ./env_vars/.env_db_oracle
   - ./env_vars/.env_srv
  secrets:
   - ORACLE_USER
   - ORACLE_PASSWORD
  depends_on:
   - zabbix-build-oracle
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-oracle
      - zabbix-server-ol-oracle
      - zabbix-server-oracle-ol
   zbx_net_frontend:
#  devices:
#   - "/dev/ttyUSB0:/dev/ttyUSB0"
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with Oracle database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "oracle"
   com.zabbix.os: "oracle linux"

 zabbix-web-nginx-oracle:
  build:
   context: ./Dockerfiles/web-nginx-oracle/ol
   cache_from:
    - oraclelinux:8-slim
   args:
    BUILD_BASE_IMAGE: zabbix-build-oracle:ol-6.4.0
  image: zabbix-web-nginx-oracle:ol-6.4.0
  ports:
   - "80:8080"
   - "443:8443"
  links:
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
   - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
#   - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
#   - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
#   - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
   - ./env_vars/.env_db_oracle
   - ./env_vars/.env_web
  secrets:
   - ORACLE_USER
   - ORACLE_PASSWORD
  depends_on:
   - zabbix-server
   - zabbix-build-oracle
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-nginx-oracle
     - zabbix-web-nginx-ol-oracle
     - zabbix-web-nginx-oracle-ol
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with Oracle database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "oracle"
   com.zabbix.os: "oracle linux"

 zabbix-agent:
  image: zabbix/zabbix-agent:ol-6.4.0
  profiles:
   - full
   - all
  ports:
   - "10050:10050"
  links:
   - zabbix-server:zabbix-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
  env_file:
   - ./env_vars/.env_agent
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-ol
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "oracle linux"

#  zabbix-java-gateway:
#   image: zabbix/zabbix-java-gateway:ol-6.4.0
#   profiles:
#    - full
#    - all
#   ports:
#    - "10052:10052"
#   deploy:
#    resources:
#     limits:
#       cpus: '0.5'
#       memory: 512M
#     reservations:
#       cpus: '0.25'
#       memory: 256M
#   env_file:
#    - ./env_vars/.env_java
#   networks:
#    zbx_net_backend:
#     aliases:
#      - zabbix-java-gateway
#      - zabbix-java-gateway-ol
#   stop_grace_period: 5s
#   labels:
#    com.zabbix.description: "Zabbix Java Gateway"
#    com.zabbix.company: "Zabbix LLC"
#    com.zabbix.component: "java-gateway"
#    com.zabbix.os: "oracle linux"

#  zabbix-snmptraps:
#   image: zabbix/zabbix-snmptraps:ol-6.4.0
#   profiles:
#    - full
#    - all
#   ports:
#    - "162:1162/udp"
#   volumes:
#    - snmptraps:/var/lib/zabbix/snmptraps:rw
#   deploy:
#    resources:
#     limits:
#       cpus: '0.5'
#       memory: 256M
#     reservations:
#       cpus: '0.25'
#       memory: 128M
#   networks:
#    zbx_net_frontend:
#     aliases:
#      - zabbix-snmptraps
#    zbx_net_backend:
#   stop_grace_period: 5s
#   labels:
#    com.zabbix.description: "Zabbix snmptraps"
#    com.zabbix.company: "Zabbix LLC"
#    com.zabbix.component: "snmptraps"
#    com.zabbix.os: "oracle linux"

#  zabbix-web-service:
#   image: zabbix/zabbix-web-service:ol-6.4.0
#   profiles:
#    - full
#    - all
#   ports:
#    - "10053:10053"
#   volumes:
#    - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
#   security_opt:
#    - seccomp:./env_vars/chrome_dp.json
#   deploy:
#    resources:
#     limits:
#       cpus: '0.5'
#       memory: 512M
#     reservations:
#       cpus: '0.25'
#       memory: 256M
#   env_file:
#    - ./env_vars/.env_web_service
#   networks:
#    zbx_net_backend:
#     aliases:
#      - zabbix-web-service
#      - zabbix-web-service-ol
#   stop_grace_period: 5s
#   labels:
#    com.zabbix.description: "Zabbix web service"
#    com.zabbix.company: "Zabbix LLC"
#    com.zabbix.component: "web-service"
#    com.zabbix.os: "oracle linux"

# elasticsearch:
#  image: elasticsearch
#  profiles:
#   - full
#   - all
#  environment:
#   - transport.host=0.0.0.0
#   - discovery.zen.minimum_master_nodes=1
#  networks:
#   zbx_net_backend:
#    aliases:
#     - elasticsearch

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  snmptraps:

secrets:
  ORACLE_USER:
    file: ./env_vars/.ORACLE_USER
  ORACLE_PASSWORD:
    file: ./env_vars/.ORACLE_PASSWORD
